name: GitHub Actions Try-Out
on: [push]
jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Windows Latest MSVC", artifact: "Windows-MSVC.tar.xz",
            os: windows-latest,
            build_type: "Release", cc: "cl", cxx: "cl",
            environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
          }
        - {
            name: "Ubuntu Latest GCC", artifact: "Linux.tar.xz",
            os: ubuntu-latest,
            build_type: "Release", cc: "gcc", cxx: "g++"
          }
    steps:
    - uses: actions/checkout@v2
    - name: git fetch
      run: git fetch --prune --unshallow --tags
    - name: mkdir
      run: mkdir build
    - name: cmake build
      run: cmake -Bbuild -S.
    - name: cmake make
      run: cmake --build build/ --config Release
    - name: check version
      run: ./build/bin/Release/Version 